{% set version='0.1.1' %}
{% set md5='a2fbed9a2a769a6fe09dac2455e82df8' %}
{% set build_number='1' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-stacktraces
  version: {{ version }}
  md5: {{ md5 }}

source:
  fn: julia-stacktraces-{{ version}}.tar.gz
  url: https://github.com/invenia/StackTraces.jl/archive/v{{ version }}.tar.gz

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}

build:
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/invenia/StackTraces.jl
  license_file: LICENSE.md
