{% set version='0.1.0' %}
{% set md5='c1aed7d453908993a16ac37f697d68ff' %}
{% set build_number='1' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-mentalist
  version: {{ version }}
  md5: {{ md5 }}

source:
  fn: julia-mentalist-{{ version}}.tar.gz
  url: https://github.com/WGS-TB/MentaLiST/archive/v0.1.0.tar.gz

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - hdf5
    - libxml2
    - julia {{ jl_range }}
    - julia-argparse
    - julia-lumberjack
    - julia-logging
    - julia-suppressor
    - julia-opengene
    - julia-bio

build:
  number: {{ build_number }}
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/WGS-TB/MentaLiST
  license_file: LICENSE
