{% set version='0.9.4' %}
{% set md5='ef99caff4eddf51336d639b064a82a59' %}
{% set build_number='0' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-compat
  version: {{ version }}
  md5: {{ md5 }}

source:
  fn: julia-compat-{{ version}}.tar.gz
  url: https://github.com/JuliaLang/Compat.jl/archive/v{{ version }}.tar.gz

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}

build:
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/JuliaLang/Compat.jl
  license_file: LICENSE.md
