{% set version='0.1.5' %}
{% set md5='9925e16857e3818221fb7638768caa08' %}
{% set build_number='0' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-polynomials
  version: {{ version }}

source:
  fn: julia-polynomials-{{ version }}.tar.gz
  url: https://github.com/JuliaMath/Polynomials.jl/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}

build:
  number: {{ build_number }}
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/JuliaMath/Polynomials.jl
  license_file: LICENSE.md
