{% set version='0.5.0' %}
{% set md5='97c29da32ac04d284db8b490ac82573f' %}
{% set build_number='0' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-argparse
  version: {{ version }}
  md5: {{ md5 }}

source:
  fn: julia-argparse-{{ version}}.tar.gz
  url: https://github.com/carlobaldassi/ArgParse.jl/archive/v{{ version }}.tar.gz

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}
    - julia-compat
    - julia-textwrap

build:
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/carlobaldassi/ArgParse.jl
  license_file: LICENSE.md
