{% set version='0.3.3' %}
{% set md5='fc7ee9dab3c5b3dc465d16b0d32897ea' %}
{% set build_number='2' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-mocking
  version: {{ version }}

source:
  fn: julia-mocking-{{ version}}.tar.gz
  url: https://github.com/invenia/Mocking.jl/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}
   
requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}
    - julia-compat

build:
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/invenia/Mocking.jl
  license_file: LICENSE.md
