{% set version='0.2.6' %}
{% set md5='94be52f1390d9e497d84552cd8787913' %}
{% set build_number='0' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-nanmath
  version: {{ version }}

source:
  fn: julia-nanmath-{{ version }}.tar.gz
  url: https://github.com/mlubin/NaNMath.jl/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}
    - julia-compat

build:
  number: {{ build_number }}
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/mlubin/NaNMath.jl
  license_file: LICENSE.md
