{% set version='0.13.0' %}
{% set md5='fc03b73d921a88dfc3d9c4ee635d5c5a' %}
{% set build_number='0' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-distributions
  version: {{ version }}

source:
  fn: julia-distributions-{{ version }}.tar.gz
  url: https://github.com/JuliaStats/Distributions.jl/archive/v{{ version }}.tar.gz
  md5: {{ md5 }}

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}
    - julia-pdmats
    - julia-statsfuns
    - julia-calculus
    - julia-statsbase
    - julia-compat
    - julia-quadgk
    - julia-specialfunctions

build:
  number: {{ build_number }}
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/JuliaStats/Distributions.jl
  license_file: LICENSE.md
