{% set version='2.1.1' %}
{% set md5='b6f0f99d2712ce5166879876056efa8e' %}
{% set build_number='2' %}

{% if environ.get("JULIA_VERSION", "0.6") == "0.6" %}
  {% set jl_range='>=0.6.0a0,<0.7a0' %}
  {% set jl_prefix='jl06' %}
{% elif environ.get("JULIA_VERSION", "0.5") == "0.5" %}
  {% set jl_range='>=0.5.0a0,<0.6a0' %}
  {% set jl_prefix='jl05' %}
{% else %}
  {% set jl_range='>=0.4.0a0,<0.5a0' %}
  {% set jl_prefix='jl04' %}
{% endif %}

package:
  name: julia-lumberjack
  version: {{ version }}
  md5: {{ md5 }}

source:
  fn: julia-lumberjack-{{ version }}.tar.gz
  url: https://github.com/WestleyArgentum/Lumberjack.jl/archive/v{{ version }}.tar.gz

requirements:
  build:
    - julia {{ jl_range }}
  run:
    - julia {{ jl_range }}
    - julia-json
    - julia-compat
    - julia-stacktraces
    - julia-mocking

build:
  number: {{ build_number }}
  string: {{ jl_prefix + '_' + build_number }}
  script_env:
    - JULIA_VERSION

about:
  home: https://github.com/WestleyArgentum/Lumberjack.jl
  license_file: LICENSE.md
